### ISSUE TITLE
missing logic

### ISSUE THREAD

**Issue by aleks-hyf** [bengu-thon-mai-mochi/hyf-homework#11]
https://github.com/bengu-thon-mai-mochi/hyf-homework/blob/7acf66ea7a0ecd0de3feea55a16342c30967bdba/javascript/javascript2/week1/return-average-median.js#L23

This function is not complete - what if `array.length % 2 == 0`

**Comment by aleks-hyf** [comment]
In fact this median function is not even correct for the case you handled. Make sure you understand what and why. Ask your classmates, or ask me.

**Comment by bengu-thon-mai-mochi** [comment]
Hello Aleks, thank you for checking my homework. I am running through your feedbacks today and I looked into this one a lot. Yet I couldn't understand how my handling of this issue is not correct because the code delivers the middle number for odd numbers. What do you mean by incomplete? Do you mean there is no "else" in function? I just didn't have time since we had other exercises and preparation was going.
